# Generated by Django 3.2.6 on 2021-08-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('publicate_on', models.DateTimeField()),
            ],
        ),
    ]
